# Generated by Django 4.1.5 on 2023-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chripsounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_transmitter', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('range_zero', models.CharField(max_length=30)),
                ('chriprate', models.CharField(max_length=30)),
            ],
        ),
    ]
