# Generated by Django 4.1.5 on 2023-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chripsounder",
            name="first_hop_range_one",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chripsounder",
            name="first_hop_range_two",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chripsounder",
            name="second_hop_range_one",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chripsounder",
            name="second_hop_range_two",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chripsounder",
            name="range_zero",
            field=models.CharField(max_length=30, verbose_name="Range ground"),
        ),
    ]
