# Generated by Django 4.1.5 on 2023-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_chripsounder_first_hop_range_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chripsounder",
            name="tx_code",
            field=models.CharField(default='CVA', max_length=30),
        ),
    ]
