# Generated by Django 4.1.5 on 2023-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_chripsounder_tx_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryInfos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "root_dir",
                    models.CharField(
                        max_length=100, verbose_name="Root Directory Path:-"
                    ),
                ),
                (
                    "output_dir",
                    models.CharField(
                        max_length=100, verbose_name="Output Directory Path:-"
                    ),
                ),
                (
                    "input_dir",
                    models.CharField(
                        max_length=100, verbose_name="Input Directory Path:-"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverInfos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=100, verbose_name="Receiver Name:-"),
                ),
                (
                    "receiver_code",
                    models.CharField(max_length=100, verbose_name="Receiver Code:-"),
                ),
                (
                    "receiver_location",
                    models.CharField(
                        max_length=100, verbose_name="Receiver Location:-"
                    ),
                ),
                (
                    "receiver_lat",
                    models.CharField(max_length=100, verbose_name="Receiver Lat:-"),
                ),
                (
                    "receiver_long",
                    models.CharField(max_length=100, verbose_name="Receiver Long:-"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="chripsounder",
            name="name_of_transmitter",
            field=models.CharField(max_length=30, verbose_name="Name of transmitter"),
        ),
        migrations.AlterField(
            model_name="chripsounder",
            name="tx_code",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
