# Generated by Django 4.1.3 on 2023-01-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_directoryinfos_receiverinfos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chripsounder",
            options={"verbose_name": "Chirpsounder"},
        ),
        migrations.AlterModelOptions(
            name="directoryinfos",
            options={"verbose_name": "DirectoryInfo"},
        ),
        migrations.AlterModelOptions(
            name="receiverinfos",
            options={"verbose_name": "ReceiverInfo"},
        ),
        migrations.AddField(
            model_name="chripsounder",
            name="receiver_code",
            field=models.CharField(
                default="W2NAF", max_length=100, verbose_name="Receiver Code:-"
            ),
            preserve_default=False,
        ),
    ]
