# Generated by Django 4.1.5 on 2023-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_chripsounder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chripsounder",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receiverinfos",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chripsounder",
            name="receiver_code",
            field=models.CharField(max_length=100, verbose_name="Receiver Code"),
        ),
    ]
